<a href="https://colab.research.google.com/github/EricAndradeNJIT/data-analytics-folder/blob/main/Standardize_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
cancer = files.upload()

Saving cancer.csv to cancer.csv

In [2]:
#import packages

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [3]:
#read and rename

cancer = pd.read_csv('cancer.csv')

cancer.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883

In [4]:
#convert diagnosis into numeric data type

cancer.loc[cancer['diagnosis'] == 'M', 'cancer_present'] = 1
cancer.loc[cancer['diagnosis'] == 'B', 'cancer_present'] = 0

In [6]:
#split data into target variable and feature of interest

y = cancer[['cancer_present']]

X = cancer[['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 
            'concavity_mean', 'concave points_mean',	'symmetry_mean',	'fractal_dimension_mean']]

In [11]:
X.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
count,569.000000,569.000000,569.000000,569.000000,565.000000,569.000000,569.000000,569.000000,564.000000,563.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096336,0.104341,0.088799,0.048919,0.181233,0.062792
std,3.524049,4.301036,24.298981,351.914129,0.014029,0.052813,0.079720,0.038803,0.027453,0.007050
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161975,0.057750
50%,13.370000,18.840000,86.240000,551.100000,0.095860,0.092630,0.061540,0.033500,0.179250,0.061550
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440

In [12]:
#Split data into training/validation dataset and test dataset

X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [13]:
#Split training/validation datasets into traning and validation sets

X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.3333, random_state=42)

In [22]:
#look at measures in trainig data

X_train.describe()

,0,1,2,3,4,5,6,7,8,9
count,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000
mean,14.326711,19.358380,93.248556,674.802817,0.095419,0.102521,0.089788,0.049496,0.180857,0.062240
std,3.603878,4.370346,24.885064,361.376372,0.013682,0.053271,0.082404,0.039230,0.026865,0.007050
min,7.691000,9.710000,47.920000,170.400000,0.052630,0.019380,0.000000,0.000000,0.116700,0.049960
25%,11.890000,16.465000,76.495000,433.525000,0.085948,0.061257,0.028445,0.020745,0.161475,0.057423
50%,13.415000,18.895000,86.470000,556.950000,0.094265,0.091280,0.064460,0.034605,0.179050,0.061085
75%,16.387500,21.685000,108.500000,838.675000,0.103525,0.130525,0.128425,0.077387,0.195750,0.065705
max,27.420000,39.280000,186.900000,2501.000000,0.163400,0.311400,0.426800,0.201200,0.265500,0.097440

In [23]:
#check for missing data

X.isna().sum()

radius_mean               0
texture_mean              0
perimeter_mean            0
area_mean                 0
smoothness_mean           4
compactness_mean          0
concavity_mean            0
concave points_mean       0
symmetry_mean             5
fractal_dimension_mean    6
dtype: int64

In [24]:
#impute data

imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

X_train_ = imp_mean.fit_transform(X_train)
                                  
X_train = pd.DataFrame(X_train_)

In [26]:
#check for missing data

X_train.isna().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [27]:
#Standardize data

std = StandardScaler()

X_train_std_ = std.fit_transform(X_train)

X_train_std = pd.DataFrame(X_train_std_)

print(round(X_train_std.describe(),2))

            0       1       2       3       4       5       6       7       8  \
count  284.00  284.00  284.00  284.00  284.00  284.00  284.00  284.00  284.00
mean     0.00    0.00    0.00    0.00   -0.00   -0.00    0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00
min     -1.84   -2.21   -1.82   -1.40   -3.13   -1.56   -1.09   -1.26   -2.39
25%     -0.68   -0.66   -0.67   -0.67   -0.69   -0.78   -0.75   -0.73   -0.72
50%     -0.25   -0.11   -0.27   -0.33   -0.08   -0.21   -0.31   -0.38   -0.07
75%      0.57    0.53    0.61    0.45    0.59    0.53    0.47    0.71    0.56
max      3.64    4.57    3.77    5.06    4.98    3.93    4.10    3.87    3.16

            9
count  284.00
mean    -0.00
std      1.00
min     -1.75
25%     -0.68
50%     -0.16
75%      0.49
max      5.00

In [28]:
# fit scaler on training data
norm = MinMaxScaler().fit(X_train)

In [29]:
# transform training data
X_train_norm_ = norm.transform(X_train)

X_train_norm = pd.DataFrame(X_train_norm_)

print(round(X_train_norm.describe(),2))

            0       1       2       3       4       5       6       7       8  \
count  284.00  284.00  284.00  284.00  284.00  284.00  284.00  284.00  284.00
mean     0.34    0.33    0.33    0.22    0.39    0.28    0.21    0.25    0.43
std      0.18    0.15    0.18    0.16    0.12    0.18    0.19    0.19    0.18
min      0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
25%      0.21    0.23    0.21    0.11    0.30    0.14    0.07    0.10    0.30
50%      0.29    0.31    0.28    0.17    0.38    0.25    0.15    0.17    0.42
75%      0.44    0.40    0.44    0.29    0.46    0.38    0.30    0.38    0.53
max      1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00

            9
count  284.00
mean     0.26
std      0.15
min      0.00
25%      0.16
50%      0.23
75%      0.33
max      1.00

In [34]:
#check normalized data

X_train_norm

,0,1,2,3,4,5,6,7,8,9
0,0.264028,0.210010,0.257735,0.146658,0.308206,0.259263,0.114667,0.153479,0.410618,0.260952
1,0.429773,0.215083,0.420060,0.265211,0.416810,0.426067,0.155834,0.268241,0.553091,0.331929
2,0.157585,0.000000,0.150022,0.080323,0.390990,0.130060,0.059302,0.084394,0.143817,0.295703
3,0.369963,0.523842,0.342639,0.226723,0.372303,0.109342,0.056186,0.144085,0.267473,0.106992
4,0.712606,0.381468,0.715067,0.566635,0.373567,0.605164,0.514292,0.540755,0.372312,0.252317
...,...,...,...,...,...,...,...,...,...,...
279,0.210300,0.304024,0.215930,0.115936,0.526045,0.452777,0.285380,0.257555,0.762097,0.590354
280,0.191545,0.213730,0.180602,0.099674,0.344227,0.135196,0.060614,0.115408,0.313844,0.289806
281,0.346647,0.325668,0.333357,0.209946,0.282116,0.200740,0.206584,0.145378,0.205645,0.157961
282,0.308125,0.120392,0.288819,0.176907,0.355241,0.146668,0.024906,0.095278,0.285618,0.192923
283,0.063815,0.204599,0.077853,0.032095,0.379074,0.359290,0.217034,0.114712,0.092742,0.456403

In [35]:
X_train_norm.describe()

,0,1,2,3,4,5,6,7,8,9
count,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000
mean,0.336343,0.326289,0.326152,0.216426,0.386284,0.284711,0.210375,0.246003,0.431164,0.258643
std,0.182669,0.147797,0.179055,0.155057,0.123515,0.182422,0.193073,0.194981,0.180547,0.148475
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.212834,0.228441,0.205605,0.112900,0.300781,0.143406,0.066647,0.103106,0.300907,0.157171
50%,0.290131,0.310619,0.277378,0.165859,0.375869,0.246216,0.151031,0.171993,0.419019,0.234309
75%,0.440798,0.404971,0.435890,0.286739,0.459466,0.380607,0.300902,0.384630,0.531250,0.331613
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000